/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio.h"
#include "Timer.h"
#include "UART.h"
#include "RCC.h"
#include "Ringbuffer.h"
#include "Interrupt.h"
#include "Flash.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

extern RingBuffer_Typedef ringbuffer;
static uint8_t is_first_write = 1; // Cờ để kiểm tra lần ghi đầu tiên
static uint32_t current_flash_address = 0x08002000;
// Địa chỉ bắt đầu của application
#define app_start_address 0x08002000
// Con trỏ hàm reset handler của application
typedef void (*appfuncpointer)(void);

void goto_app();

void setup_boot_pin(void);

int main(void)
{
	RCC_Config_HSI_8MHz();
	// Khởi tạo PC13
	GPIO_init_output(GPIOC, 13);
	// Khởi tạo gpio
	UART1_gpio_init();
	// Khởi tạo ringbuffer
	Ringbuffer_init(&ringbuffer);
	// bật baud, ngắt nvic table
	USART1_RX_Int_init();

	setup_boot_pin();

	uint8_t data;
	uint8_t tmp_data;
	uint8_t has_tmp_data = 0;
	while(1)
	{
		if((GPIOA->IDR & (1 << 5)) == 0)
		{
			if(Ringbuffer_get(&ringbuffer, &data))
			{
				if(is_first_write == 1)
				{
					// Xóa 3 page (3kb) mỗi kb ~ 0x400
					Flash_EraseOnePage(0x08002000);
					Flash_EraseOnePage(0x08002400);
					Flash_EraseOnePage(0x08002800);
					is_first_write = 0;
				}
				if(!has_tmp_data)
				{
					tmp_data = data;
					has_tmp_data = 1;
				}
				else
				{
					// Ghép temp_data và data thành 16bit
					uint16_t halfword = ((uint16_t)data << 8) | tmp_data;
					Flash_WriteHalfWord(current_flash_address, halfword);
					current_flash_address += 2;
					has_tmp_data = 0;
					GPIO_toggle_pin(GPIOC, 13);
				}
			}
		}
		else
		{
			goto_app();
		}
	}
}


void goto_app()
{
	// Lấy địa chỉ msp của app
	uint32_t app_msp = *(volatile uint32_t*)(app_start_address);
	// Lấy địa chỉ resethandler của app
	uint32_t app_rshandler = *(volatile uint32_t*)(app_start_address + 4);
	// Set msp hiện hành thành msp của app
	__asm volatile ("msr msp, %0" : : "r" (app_msp) : );
	// Set lại offset vector table của app
	*(uint32_t*)0xE000ED08 = app_start_address;
	appfuncpointer app_pointer = (appfuncpointer)app_rshandler;
	app_pointer();
	while(1);
}

void setup_boot_pin(void)
{
	// Port A RCC enable
	RCC_APB2ENR |= (1 << 2);
	// Set input
	GPIOA->CRL &= ~(0xF << 20);
	GPIOA->CRL |= (0b1000 << 20);
	// Set pullup
	GPIOA->ODR |= (1 << 5);
}
