/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "RCC.h"
#include "gpio.h"
#include "Timer.h"
#include "Interrupt.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	GPIO_init_output(GPIOC,13);
	// Enable clock for INT pin
	RCC_APB2ENR |= (1 << 2) | (1 << 0);
	// Enable INT5_9 from NVIC
	NVIC_Enable_IRQ(EXTI4_IRQ_NUM);
	// Enable Int5 from peripheral, falling edge
	EXTI_Init(GPIOA, 4, 0);
	// Clock for timer1
	enable_clock_for_timer1();
	setup_timer1();
    /* Loop forever */
	while(1)
	{
		GPIO_toggle_pin(GPIOC, 13);
		delay_1s();
	}
}
