/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "RCC.h"
#include "gpio.h"
#include "Timer.h"
#include "Interrupt.h"
#include "UART.h"
#include "Bootflags.h"
#include "Flash.h"
#include "IWDG.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

volatile uint8_t goToBootloader = 0;
// Flag
volatile flags_t* flags = ((flags_t*)ADDR_FLAGS_START);

int main(void)
{
	GPIO_init_output(GPIOC,13);
	// Clock for timer1
	enable_clock_for_timer1();
	// Setup timer1
	setup_timer1();

	UART1_gpio_init();
	// Setup UART1 (baud, nvic enable, rxint enable)
	USART1_RX_Int_init();

    /* Loop forever */
	while(1)
	{
		GPIO_toggle_pin(GPIOC, 13);
		delay_1s();
		IWDG_refresh();
		if(goToBootloader == 1)
		{
			Flash_EraseOnePage((uint32_t)ADDR_FLAGS_START);
			Flash_WriteHalfWord((uint32_t)(&(flags->magic)), (uint16_t)0xDEAD);
			Flash_WriteHalfWord((uint32_t)(&(flags->magic)) + 2, (uint16_t)0xBEFF);
			Flash_WriteHalfWord((uint32_t)(&(flags->next_action)), (uint16_t)FLAG_UPDATE_APP);
			// Soft reset, 0x05FA là key, bit 2 là bit reset
			RESET_AIRCR = (0x05FA << 16) | (1 << 2);
		}
	}
}
